import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Layout/Header";
import { Menu } from "../components/Layout/Menu";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const content = {
  panelTitle: "Clique na imagem para selecionar o modelo",
  models: [
    { name: "Kit standard: perfis + acessórios", link: '/kit-standard', imageUrl: '', id: 1 },
    { name: "Vidro com travessa", link: '/vidro-com-travessa', imageUrl: '', id: 2 },
    { name: "Vidro com lambril", link: '/vidro-com-lambril', imageUrl: '', id: 3 },
    { name: "Lambril", link: '/lambril', imageUrl: '', id: 4 },
    { name: "Vidro com veneziana", link: '/vidro-com-veneziana', imageUrl: '', id: 5 },
    { name: "Veneziana", link: '/veneziana', imageUrl: '', id: 6 },
  ]
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${montserrat.variable} antialiased`}>
        <Header title="Como comprar a Porta de Giro Montare" />
        <main className="grid md:grid-cols-2 p-4">
          <section className="order-2 md:order-1">
            <Menu pageTitle={content.panelTitle} models={content.models} />
          </section>
          <section className="order-1 md:order-2 text-center bg-white rounded-lg border-dashed border-orange border p-4">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
